#!/bin/bash

OUTPUT_DIR=~/Dropbox/Public

DIST_NAME=BitSafe

if [ -z "$1" ]; then
	echo "usage: release <version>"
	exit 1
fi

function processfile {
        gpg -bs $1 || return $?
	cp $1 $TODIR
	mv $1.sig $TODIR
	return $?
}

function exiterr {
	echo "error, exiting."
	exit 1
}


if [ ! -d $OUTPUT_DIR ]; then
	echo "no output directory"
	exit 1
fi

if [ ! -e binary.img ] || [ ! -e binary/live/filesystem.squashfs ]; then
	echo "missing binary.img or filesystem.squashfs"
	exit 1
fi
TODIR=$OUTPUT_DIR/$1
test -d $TODIR || mkdir -p $TODIR
if [ ! -d $TODIR ]; then
        echo "no output directory"
        exit 1
fi

BINARY_FILE=$DIST_NAME\_V$1\_image.img
UPDATE_FILE=$DIST_NAME\_V$1\_update.zip

ln -s binary.img "$BINARY_FILE" || exiterr
processfile "$BINARY_FILE" || exiterr
rm "$BINARY_FILE"

cd binary || exiterr 
#tar -czf ../live.tar.gz live || exiterr
zip -r ../"$UPDATE_FILE" live || exiterr
cd ..
processfile "$UPDATE_FILE" || exiterr
rm "$UPDATE_FILE" || exiterr

echo ""
echo "Calculating MD5 hash..."
cd $TODIR 
md5sum "$BINARY_FILE" "$UPDATE_FILE"
