#!/bin/bash

. /lib/bitsafe-func

check_su

find_drive
CRYPT_DEVICE=/dev/"$DRIVE"2

if [ "$DISPLAY" ]; then GUI_MODE=1; fi

if [ "$DRIVE" ] && [ -e "/dev/$DRIVE" ] && [ ! -e "$CRYPT_DEVICE" ]; then
	notify "`gettext \
\"No persistent storage partition found.
I will now start the BitSafe storage format utility.\"`"
	test -f /tmp/succesful_format && rm /tmp/succesful_format
	if [ "$DISPLAY" ]; then lxterminal -e /usr/sbin/bitsafe-format-storage -u
	else /usr/sbin/bitsafe-format-storage -u
	fi
	if [ ! -e /tmp/succesful_format ]; then exit 1; fi
fi
	
/usr/sbin/bitsafe-mount-storage

