#!/bin/bash

#Flush
iptables -F

#Blocca connessioni in entrata eccetto traffico di risposta
iptables -P INPUT DROP
iptables -A INPUT -m state --state ESTABLISHED -j ACCEPT

#Permetti traffico in uscita
iptables -P OUTPUT ACCEPT #ridondante

