#!/bin/bash

#First it creates the updated localization base file (localization.po), then it compiles all available .po localizations to .mo in /usr/share/locale,
#using the Language field to route them

xgettext -L shell -o /usr/share/bitsafe/localization.po /usr/sbin/bitsafe-* /usr/bin/bitsafe-* /lib/bitsafe-* /lib/strings/bitsafe-* /usr/bin/storage_wrappers/*
cd /usr/share/bitsafe/localizations

if [ "`ls`" ]; then
	for loc in *.po; do
		LANG_CODE=`cat $loc | egrep -o "^\"Language: [^\"]+\"$" | egrep -o ": [^\\]+" | egrep -o "[^: ]+"`
		if [ -z "$LANG_CODE" ]; then
			echo "Localization file $loc miss a proper Language header. I need it in order to place it correctly."
			exit 1
		else
			echo "Adding $LANG_CODE localization..."
			OUTDIR=/usr/share/locale/$LANG_CODE/LC_MESSAGES
			mkdir -p $OUTDIR
			msgfmt $loc -o $OUTDIR/bitsafe.mo
		fi
	done	
fi
