#!/bin/bash

# Install stuff in bitsafe.build.config
if [ "$PRECONF_PACKETADD" ]; then apt-get --assume-yes install $PRECONF_PACKETADD; fi

# uninstall useless things. Anyone knows how to prevent them to be installed in the first place?
if [ "$PRECONF_PACKETREM" ]; then apt-get --assume-yes purge $PRECONF_PACKETREM; fi

apt-get --assume-yes autoremove --purge
apt-get clean

exit 0
