# Mozilla User Preferences

/* Do not edit this file.
 *
 * If you make changes to this file while the application is running,
 * the changes will be overwritten when the application exits.
 *
 * To make a manual change to preferences, you can visit the URL about:config
 * For more information, see http://www.mozilla.org/unix/customizing.html#prefs
 */

user_pref("app.update.lastUpdateTime.addon-background-update-timer", 1322607601);
user_pref("app.update.lastUpdateTime.background-update-timer", 1322607601);
user_pref("app.update.lastUpdateTime.blocklist-background-update-timer", 1322607601);
user_pref("app.update.lastUpdateTime.microsummary-generator-update-timer", 1322607601);
user_pref("app.update.lastUpdateTime.places-maintenance-timer", 1322607601);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 1322607601);
user_pref("browser.download.dir", "/tmp");
user_pref("browser.download.folderList", 2);
user_pref("browser.history_expire_days.mirror", 180);
user_pref("browser.migration.version", 1);
user_pref("browser.places.importBookmarksHTML", false);
user_pref("browser.places.smartBookmarksVersion", 1);
user_pref("browser.preferences.advanced.selectedTabIndex", 3);
user_pref("browser.privatebrowsing.autostart", true);
user_pref("browser.safebrowsing.remoteLookups", false);
user_pref("browser.sessionstore.resume_session_once", true);
user_pref("browser.startup.homepage", "http://bitcoinwatch.com/");
user_pref("browser.startup.homepage_override.mstone", "rv:1.9.1.16");
user_pref("capability.policy.maonoscript.javascript.enabled", "allAccess");
user_pref("capability.policy.maonoscript.sites", "addons.mozilla.org dropbox.com flashgot.net google.com googleapis.com gstatic.com hotmail.com informaction.com live.com maone.net mozilla.net msn.com noscript.net passport.com passport.net passportimages.com paypal.com paypalobjects.com securecode.com wlxrs.com yahoo.com yahooapis.com yimg.com youtube.com ytimg.com about: about:addons about:blank about:blocked about:certerror about:config about:crashes about:credits about:home about:neterror about:plugins about:privatebrowsing about:sessionrestore chrome: http://dropbox.com http://flashgot.net http://google.com http://googleapis.com http://gstatic.com http://hotmail.com http://informaction.com http://live.com http://maone.net http://mozilla.net http://msn.com http://noscript.net http://passport.com http://passport.net http://passportimages.com http://paypal.com http://paypalobjects.com http://securecode.com http://wlxrs.com http://yahoo.com http://yahooapis.com http://yimg.com http://youtube.com http://ytimg.com https://dropbox.com https://flashgot.net https://google.com https://googleapis.com https://gstatic.com https://hotmail.com https://informaction.com https://live.com https://maone.net https://mozilla.net https://msn.com https://noscript.net https://passport.com https://passport.net https://passportimages.com https://paypal.com https://paypalobjects.com https://securecode.com https://wlxrs.com https://yahoo.com https://yahooapis.com https://yimg.com https://youtube.com https://ytimg.com resource:");
user_pref("extensions.enabledItems", "{73a6fe31-595d-460b-a920-fcc0f8843232}:2.2.1,{e0204bd5-9d31-402b-a99d-a6aa8ffebdca}:1.4.4.1,{972ce4c6-7e08-4474-a285-3208198ce6fd}:3.5.16");
user_pref("extensions.lastAppVersion", "3.5.16");
user_pref("extensions.torbutton.fresh_install", false);
user_pref("extensions.torbutton.http_port", 8118);
user_pref("extensions.torbutton.http_proxy", "127.0.0.1");
user_pref("extensions.torbutton.https_port", 8118);
user_pref("extensions.torbutton.https_proxy", "127.0.0.1");
user_pref("extensions.torbutton.inserted_button", true);
user_pref("extensions.torbutton.normal_exit", true);
user_pref("extensions.torbutton.saved.ftp_port", 8118);
user_pref("extensions.torbutton.saved.ftp_proxy", "127.0.0.1");
user_pref("extensions.torbutton.saved.gopher_port", 8118);
user_pref("extensions.torbutton.saved.gopher_proxy", "127.0.0.1");
user_pref("extensions.torbutton.saved.http_port", 8118);
user_pref("extensions.torbutton.saved.http_proxy", "127.0.0.1");
user_pref("extensions.torbutton.saved.https_port", 8118);
user_pref("extensions.torbutton.saved.https_proxy", "127.0.0.1");
user_pref("extensions.torbutton.saved.no_proxies_on", "127.0.0.1");
user_pref("extensions.torbutton.saved.share_proxy_settings", true);
user_pref("extensions.torbutton.saved.socks_host", "127.0.0.1");
user_pref("extensions.torbutton.saved.socks_port", 8118);
user_pref("extensions.torbutton.saved.socks_remote_dns", true);
user_pref("extensions.torbutton.saved.socks_version", 5);
user_pref("extensions.torbutton.saved.type", 1);
user_pref("extensions.torbutton.socks_host", "127.0.0.1");
user_pref("extensions.torbutton.socks_port", 9050);
user_pref("extensions.torbutton.startup", true);
user_pref("extensions.torbutton.tz_string", "UTC+00:00");
user_pref("extensions.update.notifyUser", false);
user_pref("intl.charsetmenu.browser.cache", "ISO-8859-1, UTF-8");
user_pref("network.cookie.prefsMigrated", true);
user_pref("network.proxy.backup.ftp", "");
user_pref("network.proxy.backup.ftp_port", 0);
user_pref("network.proxy.backup.gopher", "");
user_pref("network.proxy.backup.gopher_port", 0);
user_pref("network.proxy.backup.socks", "127.0.0.1");
user_pref("network.proxy.backup.socks_port", 9050);
user_pref("network.proxy.backup.ssl", "127.0.0.1");
user_pref("network.proxy.backup.ssl_port", 8118);
user_pref("network.proxy.ftp", "127.0.0.1");
user_pref("network.proxy.ftp_port", 8118);
user_pref("network.proxy.gopher", "127.0.0.1");
user_pref("network.proxy.gopher_port", 8118);
user_pref("network.proxy.http", "127.0.0.1");
user_pref("network.proxy.http_port", 8118);
user_pref("network.proxy.no_proxies_on", "127.0.0.1");
user_pref("network.proxy.share_proxy_settings", true);
user_pref("network.proxy.socks", "127.0.0.1");
user_pref("network.proxy.socks_port", 8118);
user_pref("network.proxy.socks_remote_dns", true);
user_pref("network.proxy.ssl", "127.0.0.1");
user_pref("network.proxy.ssl_port", 8118);
user_pref("network.proxy.type", 0);
user_pref("network.security.ports.banned", "8118,8123,9050,9051");
user_pref("noscript.ABE.migration", 1);
user_pref("noscript.gtemp", "");
user_pref("noscript.policynames", "");
user_pref("noscript.subscription.lastCheck", -239650293);
user_pref("noscript.temp", "");
user_pref("noscript.version", "2.2.1");
user_pref("permissions.memory_only", false);
user_pref("pref.advanced.javascript.disable_button.advanced", false);
user_pref("pref.browser.homepage.disable_button.current_page", false);
user_pref("privacy.sanitize.migrateFx3Prefs", true);
user_pref("security.enable_java", false);
user_pref("security.warn_viewing_mixed", false);
user_pref("signon.rememberSignons", false);
user_pref("spellchecker.dictionary", "en_US");
user_pref("urlclassifier.keyupdatetime.https://sb-ssl.google.com/safebrowsing/newkey", 1325199305);
user_pref("xpinstall.whitelist.add", "");
user_pref("xpinstall.whitelist.add.103", "");
